# Only used for testing the docker images
version: '3'
services:
  elasticsearch-default:
    image: elasticsearch:test
    environment:  
       - cluster.name=elasticsearch-default
       - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536   
    ports:
      - "9200"
  elasticsearch-oss:
    image: elasticsearch-oss:test
    environment:  
       - cluster.name=elasticsearch-oss
       - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200"
