steps:
  - label: "debug-saml-tests-checkPart2-{{matrix}}"
    command: .ci/scripts/run-gradle.sh -Dignore.tests.seed checkPart2  --no-build-cache
    timeout_in_minutes: 300
    matrix:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "7"
      - "8"
      - "9"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "20"
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
