steps:
  - label: "debug-saml-tests-checkPart2-{{matrix}}"
    command: .ci/scripts/run-gradle.sh -Dignore.tests.seed checkPart2  --no-build-cache
    timeout_in_minutes: 300
    matrix:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "7"
      - "8"
      - "9"
      - "11"
      - "12"
      - "13"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
      - "21"
      - "22"
      - "23"
      - "24"
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
      - "35"
      - "36"
      - "37"
      - "38"
      - "39"
      - "40"
      - "41"
      - "42"
      - "43"
      - "44"
      - "45"
      - "46"
      - "47"
      - "48"
      - "49"
      - "50"
    agents:
      provider: gcp
      image: family/elasticsearch-ubuntu-2004
      machineType: custom-32-98304
      buildDirectory: /dev/shm/bk
