config:
  skip-labels:
    - ">test-mute"
    - ":Delivery/Packaging"
steps:
  - group: packaging-tests-unix-sample
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} / packaging-tests-unix-sample"
        key: "packaging-tests-unix-sample"
        command: ./.ci/scripts/packaging-test.sh $$PACKAGING_TASK
        timeout_in_minutes: 300
        matrix:
          setup:
            image:
              - rhel-8
              - ubuntu-2004
            PACKAGING_TASK:
              - destructiveDistroTest.docker
              - destructiveDistroTest.packages
              - destructiveDistroTest.archives
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          diskSizeGb: 350
          machineType: custom-16-32768
          preemptible: true
        retry:
          automatic:
            - exit_status: "-1"
              limit: 3
              signal_reason: none
            - signal_reason: agent_stop
              limit: 3

        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
