config:
  skip-labels:
    - ">test-mute"
    - ":Delivery/Packaging"
steps:
  - group: packaging-tests-unix-sample
    steps:
      - label: "{{matrix.image}} / {{matrix.PACKAGING_TASK}} / packaging-tests-unix-sample"
        command: ./.ci/scripts/packaging-test.sh --build-cache -Dorg.elasticsearch.build.cache.url=https://gradle-enterprise.elastic.co/cache/ $$PACKAGING_TASK
        timeout_in_minutes: 300
        matrix:
          setup:
            image:
              - family/elasticsearch-rhel-8
              - family/elasticsearch-ubuntu-2004
            PACKAGING_TASK:
              - destructiveDistroTest.docker
              - destructiveDistroTest.packages
              - destructiveDistroTest.archives
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          diskSizeGb: 350
          machineType: custom-16-32768
        env:
          PACKAGING_TASK: "{{matrix.PACKAGING_TASK}}"
