xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
xpack.security.http.ssl.enabled: false
cluster.name: test-cluster
node.name: node-0
#cluster.initial_master_nodes:
#  - node-0
#  - node-1
#  - node-2
#discovery.seed_hosts:
#  - localhost:9300
#  - localhost:9301
#  - localhost:9302