steps:
  - group: bwc
    steps: $BWC_STEPS
  - group: java-fips-matrix
    steps:
      - label: "{{matrix.ES_RUNTIME_JAVA}} / {{matrix.GRADLE_TASK}} / java-fips-matrix"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true -Dtests.fips.enabled=true $$GRADLE_TASK
        timeout_in_minutes: 300
        matrix:
          setup:
            ES_RUNTIME_JAVA:
              - openjdk17
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - checkRestCompat
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          preemptible: true
          buildDirectory: /dev/shm/bk
        env:
          ES_RUNTIME_JAVA: "{{matrix.ES_RUNTIME_JAVA}}"
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
      - label: "{{matrix.ES_RUNTIME_JAVA}} / {{matrix.BWC_VERSION}} / java-fips-matrix-bwc"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true -Dtests.fips.enabled=true v$$BWC_VERSION#bwcTest
        timeout_in_minutes: 300
        matrix:
          setup:
            ES_RUNTIME_JAVA:
              - openjdk17
            BWC_VERSION: $BWC_LIST
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          preemptible: true
          buildDirectory: /dev/shm/bk
        env:
          ES_RUNTIME_JAVA: "{{matrix.ES_RUNTIME_JAVA}}"
          BWC_VERSION: "{{matrix.BWC_VERSION}}"
  - group: java-matrix
    steps:
      - label: "{{matrix.ES_RUNTIME_JAVA}} / {{matrix.GRADLE_TASK}} / java-matrix"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true $$GRADLE_TASK
        timeout_in_minutes: 300
        matrix:
          setup:
            ES_RUNTIME_JAVA:
              - graalvm-ce17
              - openjdk17
              - openjdk21
              - openjdk22
            GRADLE_TASK:
              - checkPart1
              - checkPart2
              - checkPart3
              - checkRestCompat
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          preemptible: true
          buildDirectory: /dev/shm/bk
        env:
          ES_RUNTIME_JAVA: "{{matrix.ES_RUNTIME_JAVA}}"
          GRADLE_TASK: "{{matrix.GRADLE_TASK}}"
      - label: "{{matrix.ES_RUNTIME_JAVA}} / {{matrix.BWC_VERSION}} / java-matrix-bwc"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true v$$BWC_VERSION#bwcTest
        timeout_in_minutes: 300
        matrix:
          setup:
            ES_RUNTIME_JAVA:
              - graalvm-ce17
              - openjdk17
              - openjdk21
              - openjdk22
            BWC_VERSION: $BWC_LIST
        agents:
          provider: gcp
          image: family/elasticsearch-ubuntu-2004
          machineType: n1-standard-32
          preemptible: true
          buildDirectory: /dev/shm/bk
        env:
          ES_RUNTIME_JAVA: "{{matrix.ES_RUNTIME_JAVA}}"
          BWC_VERSION: "{{matrix.BWC_VERSION}}"
  - group: platform-support-unix
    steps:
      - label: "{{matrix.image}} / platform-support-unix"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true functionalTests
        timeout_in_minutes: 420
        matrix:
          setup:
            image:
              - centos-7
              - debian-10
              - debian-11
              - opensuse-leap-15
              - oraclelinux-7
              - oraclelinux-8
              - sles-12
              - sles-15
              - ubuntu-1804
              - ubuntu-2004
              - ubuntu-2204
              - rocky-8
              - rocky-9
              - rhel-7
              - rhel-8
              - rhel-9
              - almalinux-8
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          localSsds: 1
          localSsdInterface: nvme
          machineType: n1-standard-32
          preemptible: true
        env: {}
