steps:
  - group: platform-support-unix
    steps:
      - label: "{{matrix.image}} / platform-support-unix"
        command: .ci/scripts/run-gradle.sh -Dbwc.checkout.align=true functionalTests
        timeout_in_minutes: 420
        matrix:
          setup:
            image:
              - ubuntu-2004
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          localSsds: 1
          localSsdInterface: nvme
          machineType: n1-standard-96
        env: {}
