      - label: "{{matrix.image}} / $BWC_VERSION / packaging-tests-upgrade"
        command: ./.ci/scripts/packaging-test.sh -Dbwc.checkout.align=true destructiveDistroUpgradeTest.v$BWC_VERSION
        timeout_in_minutes: 300
        matrix:
          setup:
            image:
              - rocky-8
              - ubuntu-2004
        agents:
          provider: gcp
          image: family/elasticsearch-{{matrix.image}}
          machineType: n1-standard-16
          buildDirectory: /dev/shm/bk
          preemptible: true
        env:
          BWC_VERSION: $BWC_VERSION
        retry:
          automatic:
            - exit_status: "-1"
              limit: 3
              signal_reason: none
            - signal_reason: agent_stop
              limit: 3
